
DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE TEST CASCADE CONSTRAINTS; 
CREATE TABLE STUDENT
(
 ID CHAR(4),
 Name VARCHAR2(20),
 Major VARCHAR(3),

 PRIMARY KEY (ID)
);

CREATE TABLE TEST
(
 ID  CHAR(4),
 Exam VARCHAR2(10),
 Score NUMBER(3,0)  
  CHECK (Score >= 0 AND Score <= 100),

 PRIMARY KEY (ID, Exam),

 FOREIGN KEY (ID)
  REFERENCES STUDENT(ID)
);