INSERT INTO STUDENT VALUES('1716', 'James Wagner', 'CS');
INSERT INTO STUDENT VALUES('2804', 'Vassil Roussev', 'SE');
INSERT INTO STUDENT VALUES('1996', 'Ben Samuel', 'IS');
INSERT INTO STUDENT VALUES('1130', 'Chris Summa', 'CS');

INSERT INTO TEST VALUES('1716', 'Midterm', 88);
INSERT INTO TEST VALUES('1996', 'Midterm', 90);
INSERT INTO TEST VALUES('1130', 'Midterm', 93);
INSERT INTO TEST VALUES('2804', 'Midterm', 92);
INSERT INTO TEST VALUES('2804', 'Final', 97);
INSERT INTO TEST VALUES('1716', 'Final', 100);

SELECT * FROM STUDENT;

SELECT * FROM TEST;
