INSERT INTO patient VALUES('P01', 'Taylor Swift', 37, 'D01');
INSERT INTO patient VALUES('P02', 'Bruno Mars', 31, 'D04');
INSERT INTO patient VALUES('P03', 'Justin Bieber', 29, 'D07');
INSERT INTO patient VALUES('P04', 'Adele', 34, 'D10');
INSERT INTO patient VALUES('P05', 'Lady Gaga', 35, 'D02');
INSERT INTO patient VALUES('P06', 'Katy Perry', 40, 'D05');
INSERT INTO patient VALUES('P07', 'Rihanna', 39, 'D08');
INSERT INTO patient VALUES('P08', 'Chappell Roan', 27, 'D11');
INSERT INTO patient VALUES('P09', 'Ariana Grande', 32, 'D12');
INSERT INTO patient VALUES('P10', 'Alicia Keys', 36, 'D01');
INSERT INTO patient VALUES('P11', 'Post Malone', 29, 'D02');
INSERT INTO patient VALUES('P12', 'Beyonce', 37, 'D05');
INSERT INTO patient VALUES('P13', 'Britney Spears', 38, 'D08');
INSERT INTO patient VALUES('P14', 'Drake', 45, 'D23');
INSERT INTO patient VALUES('P15', 'Doja Cat', 23, 'D19');
INSERT INTO patient VALUES('P16', 'Harry Styles', 33, 'D13');
INSERT INTO patient VALUES('P17', 'Dua Lipa', 28, 'D04');
INSERT INTO patient VALUES('P18', 'Lizzo', 29, 'D12');
INSERT INTO patient VALUES('P19', 'Kendrick Lamar', 38, 'D11');
INSERT INTO patient VALUES('P20', 'Miley Cyrus', 48, 'D02');
INSERT INTO patient VALUES('P21', 'Ozzy Osbourne', 19, 'D05');
INSERT INTO patient VALUES('P22', 'Shakira', 44, 'D15');
INSERT INTO patient VALUES('P23', 'Kermit Ruffins', 42, 'D06');
INSERT INTO patient VALUES('P24', 'Eminem', 60, 'D17');
INSERT INTO patient VALUES('P25', 'Rob Zombie', 70, 'D14');
INSERT INTO patient VALUES('P26', 'Axl Rose', 66, 'D22');
INSERT INTO patient VALUES('P27', 'Billy Corgan', 58, 'D16');
INSERT INTO patient VALUES('P28', 'Justin Timberlake', 49, 'D18');
INSERT INTO patient VALUES('P29', 'Karen O', 47, 'D23');
INSERT INTO patient VALUES('P30', 'Cardi B', 33, 'D08');
commit;