INSERT INTO physician VALUES('D01', 'Anthony Mackie', 'Dermatology');
INSERT INTO physician VALUES('D02', 'Margot Robbie', 'Anesthesiology');
INSERT INTO physician VALUES('D03', 'Ryan Gosling', 'Family Medicine');
INSERT INTO physician VALUES('D04', 'Dwayne Johnson', 'Surgery');
INSERT INTO physician VALUES('D05', 'Emma Stone', 'Internal Medicine');
INSERT INTO physician VALUES('D06', 'Tom Hanks', 'Dermatology');
INSERT INTO physician VALUES('D07', 'Idris Elba', 'Anesthesiology');
INSERT INTO physician VALUES('D08', 'Gal Gadot', 'Family Medicine');
INSERT INTO physician VALUES('D09', 'Will Ferrell', 'Internal Medicine');
INSERT INTO physician VALUES('D10', 'Chris Evans', 'Dermatology');
INSERT INTO physician VALUES('D11', 'Jamie Foxx', 'Surgery');
INSERT INTO physician VALUES('D12', 'Tom Hardy', 'Anesthesiology');
INSERT INTO physician VALUES('D13', 'Rami Malek', 'Psychiatry');
INSERT INTO physician VALUES('D14', 'Vin Diesel', 'Psychiatry');
INSERT INTO physician VALUES('D15', 'Adam Driver', 'Cardiology');
INSERT INTO physician VALUES('D16', 'Scarlett Johansson', 'Family Medicine');
INSERT INTO physician VALUES('D17', 'Miles Teller', 'Cardiology');
INSERT INTO physician VALUES('D18', 'Salma Hayek', 'Psychiatry');
INSERT INTO physician VALUES('D19', 'Russell Crowe', 'Family Medicine');
INSERT INTO physician VALUES('D20', 'Ewan McGregor', 'Surgery');
INSERT INTO physician VALUES('D21', 'Ryan Reynolds', 'Family Medicine');
INSERT INTO physician VALUES('D22', 'Tom Cruise', 'Dermatology');
INSERT INTO physician VALUES('D23', 'Natalie Portman', 'Family Medicine');
commit;